config/routes.rb
Rails.application.routes.draw do
  get 'carrinho', to: 'carrinho#show'
  post 'carrinho/add'
  post 'carrinho/remove'
  get 'relatorios', to: 'relatorios#show'
  get 'pedido', to: 'pedido#show'
  resources :formapagamentos
  resources :enderecos
  resources :produtos
  root to: "home#index"
  devise_for :users, controllers: {
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/carrinho.rb
class Carrinho < ApplicationRecord
  has_many :itenspedido
  has_many :produto, through: :itenspedido

  def total
    itenspedido.to_a.sum { |item| item.total }
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :user
end

app/models/formapagamento.rb
class Formapagamento < ApplicationRecord
  belongs_to :user
end

app/models/itenspedido.rb
class Itenspedido < ApplicationRecord
  belongs_to :produto
  belongs_to :carrinho

  def total
    produto.valor * qtd
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
    belongs_to :order

  # LOGIC
  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  has_many :itenspedido
  has_many :enderecos, through: :user
  has_many :produto, through: :itenspedido

end

app/models/produto.rb
class Produto < ApplicationRecord
  def self.search(search)
    if search
      produto = Produto.where("nome LIKE ?", "%" + search + "%" )
      if produto
        self.where(id: produto)
      else
        Produto.all
      end
    else
      Produto.all
    end
  end
end

app/models/produtos.rb
class Produtos < ApplicationRecord
  has_many :itenspedido
  has_many :carrinhos, through: :itenspedido

  self.table_name = "produtos"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :enderecos
  has_many :formapagamento
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2, :facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.full_name = auth.info.name
      user.avatar_url = auth.info.image
      # If using confirmable emails and want to skip it, uncomment line below
      # user.skip_confirmation!
    end
  end
end

app/helpers/carrinho_helper.rb
module CarrinhoHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pedido_helper.rb
module PedidoHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/relatorios_helper.rb
module RelatoriosHelper
end

app/views/add_enderecos/_form.html.erb
<%= simple_form_for(@add_endereco) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :endereco %>
    <%= f.input :tipo_endereco %>
    <%= f.input :complemento %>
    <%= f.input :numero %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/layouts/store/_footer.html.erb
<footer class="py-2 bg-danger mt-10 fixed-bottom">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Dever's Food - <%= Date.today.year %></p></div>
</footer>

app/views/layouts/store/_nav.html.erb
<%# <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#!">Ai fudi</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">All Products</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                        <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <button class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    Cart
                    <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                </button>
            </form>
        </div>
    </div>
</nav> %>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%# <%= image_tag('/assets/logo.png', width: "5%", class: "mx-2") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link btn btn-light m-1" href=<%= root_path %>>Dever's Food</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link btn btn-light m-1" href="#">Entregador</a>
    </li>
    <li class="nav-item">
      <a class="nav-link btn btn-light m-1" href="#">Restaurante e Mercado</a>
    </li>
    <li class="nav-item">
      <a class="nav-link btn btn-light m-1" href="#">Carreiras</a>
    </li>
  </ul>
</div>
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? || current_user %>
    <li><%= button_to " Carrinho", "carrinho", class: "bi bi-cart btn btn-danger m-1", method: :get %></li>
    <% if @carrinho.itenspedido.count > 0 %>
    <%= button_to "Finalizar Pedido", 'pedido#show', class: "btn btn-success m-1", method: :get %>
    <% end %>
    <%= button_to "Pagamento", formapagamentos_path, class: "btn btn-light m-1", method: :get %>
    <%= button_to "Endereços", enderecos_path, class: "btn btn-light m-1", method: :get %>
    <%= button_to "Produtos", produtos_path, class: "btn btn-light m-1", method: :get %>
    <%= button_to "Editar Dados", edit_user_registration_path, class: "btn btn-light m-1", method: :get %>
    <li><%= button_to "Logout", destroy_user_session_path, method: :get, class: "btn btn-outline-danger m-1" %> </li>
  <% else %>
    <li><%= button_to "Entrar", new_user_session_path, class: "btn btn-danger m-1" %> </li>
    <li><%= button_to "Cadastre-se", new_user_registration_path, method: :get, class: "btn btn-outline-danger m-1" %>
    <% end %>
  </ul>
  <% if current_user %>
    <%= image_tag(current_user.avatar_url, width: "5%", class: "mx-2") %>
  <% end %>
</nav>

app/views/layouts/store/_produto.html.erb
<div class="col mb-5">
  <div class="card h-100">
    <!-- Product image-->
    <img class="card-img-top" src=<%= prod.img %> alt=<%= prod.descricao %> />
    <!-- Product details-->
    <div class="card-body p-4">
      <div class="text-center">
        <!-- Product name-->
        <h5 class="fw-bolder"><%= prod.nome %></h5>
        <h7><%= prod.descricao %></h7><br>
      </div>
    </div>
    <!-- Product actions-->
    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
      <!-- Product price-->
      <div class="text-center">
        <p class="btn btn-success mt-auto" > R$ <%= sprintf('%.2f', prod.valor).to_s.gsub('.', ',') %> </p>
      </div>
      <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Comprar</a></div>
    </div>
  </div>
</div>