config/routes.rb
Rails.application.routes.draw do
  get 'carrinho', to: 'carrinho#show'
  post 'carrinho/add'
  post 'carrinho/remove'
  get 'relatorios', to: 'relatorios#show'
  get 'pedido', to: 'pedido#show'
  resources :formapagamentos
  resources :enderecos
  resources :produtos
  root to: "home#index"
  devise_for :users, controllers: {
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/carrinho.rb
class Carrinho < ApplicationRecord
  has_many :itenspedido
  has_many :produto, through: :itenspedido

  def total
    itenspedido.to_a.sum { |item| item.total }
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :user
end

app/models/formapagamento.rb
class Formapagamento < ApplicationRecord
  belongs_to :user
end

app/models/itenspedido.rb
class Itenspedido < ApplicationRecord
  belongs_to :produto
  belongs_to :carrinho

  def total
    produto.valor * qtd
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
    belongs_to :order

  # LOGIC
  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  has_many :itenspedido
  has_many :enderecos, through: :user
  has_many :produto, through: :itenspedido

end

app/models/produto.rb
class Produto < ApplicationRecord
  def self.search(search)
    if search
      produto = Produto.where("nome LIKE ?", "%" + search + "%" )
      if produto
        self.where(id: produto)
      else
        Produto.all
      end
    else
      Produto.all
    end
  end
end

app/models/produtos.rb
class Produtos < ApplicationRecord
  has_many :itenspedido
  has_many :carrinhos, through: :itenspedido

  self.table_name = "produtos"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :enderecos
  has_many :formapagamento
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2, :facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.full_name = auth.info.name
      user.avatar_url = auth.info.image
      # If using confirmable emails and want to skip it, uncomment line below
      # user.skip_confirmation!
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @produtos = Produto.search(params[:search])
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:nome, :img, :descricao, :valor, :categoria, :search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carrinho_helper.rb
module CarrinhoHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pedido_helper.rb
module PedidoHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/relatorios_helper.rb
module RelatoriosHelper
end

app/views/produtos/_form.html.erb
<%= simple_form_for(@produto) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :img %>
    <%= f.input :descricao %>
    <%= f.input :valor %>
    <%= f.input :categoria %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<div id="<%= dom_id produto %>">
  <tr>
    <td>
      <strong>Nome:</strong>
      <%= produto.nome %>
    </td>

    <td>
      <strong>Link imagem:</strong>
      <%= produto.img.present? ? "Sim" : "Não" %>
    </td>

    <td>
      <strong>Descrição:</strong>
      <%= produto.descricao %>
    </td>

    <td>
      <strong>Valor:</strong>
      <%= produto.valor %>
    </td>

    <td>
      <strong>Categoria:</strong>
      <%= produto.categoria %>
    </td>
  </tr>
</div>

app/views/produtos/edit.html.erb
<h1>Editar produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Mostrar produto", @produto, class: 'btn btn-dark' %> |
  <%= link_to "Voltar para produtos", produtos_path %>
</div>

app/views/produtos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Produtos</h1>

<%= link_to "Novo produto", new_produto_path, class: 'btn btn-primary' %>

<div id="produtos">
<br>
  <% @produtos.each do |produto| %>
    <%= render produto %>
    <p>
      <%= link_to "Mostrar produto", produto, class: 'btn btn-dark' %>
    </p>
  <% end %>
</div>

app/views/produtos/new.html.erb
<h1>Novo produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Voltar para produtos", produtos_path %>
</div>

app/views/produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @produto %>

<div>
  <%= link_to "Editar produto", edit_produto_path(@produto), class: 'btn btn-warning' %>
  <%= link_to "Voltar para produtos", produtos_path, class: 'btn btn-info' %>
  <%= link_to "Excluir produto", @produto, method: :delete, class: 'btn btn-danger'  %>
  <br>
</div>