config/routes.rb
Rails.application.routes.draw do
  get 'carrinho', to: 'carrinho#show'
  post 'carrinho/add'
  post 'carrinho/remove'
  get 'relatorios', to: 'relatorios#show'
  get 'pedido', to: 'pedido#show'
  resources :formapagamentos
  resources :enderecos
  resources :produtos
  root to: "home#index"
  devise_for :users, controllers: {
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/carrinho.rb
class Carrinho < ApplicationRecord
  has_many :itenspedido
  has_many :produto, through: :itenspedido

  def total
    itenspedido.to_a.sum { |item| item.total }
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :user
end

app/models/formapagamento.rb
class Formapagamento < ApplicationRecord
  belongs_to :user
end

app/models/itenspedido.rb
class Itenspedido < ApplicationRecord
  belongs_to :produto
  belongs_to :carrinho

  def total
    produto.valor * qtd
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
    belongs_to :order

  # LOGIC
  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  has_many :itenspedido
  has_many :enderecos, through: :user
  has_many :produto, through: :itenspedido

end

app/models/produto.rb
class Produto < ApplicationRecord
  def self.search(search)
    if search
      produto = Produto.where("nome LIKE ?", "%" + search + "%" )
      if produto
        self.where(id: produto)
      else
        Produto.all
      end
    else
      Produto.all
    end
  end
end

app/models/produtos.rb
class Produtos < ApplicationRecord
  has_many :itenspedido
  has_many :carrinhos, through: :itenspedido

  self.table_name = "produtos"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :enderecos
  has_many :formapagamento
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2, :facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.full_name = auth.info.name
      user.avatar_url = auth.info.image
      # If using confirmable emails and want to skip it, uncomment line below
      # user.skip_confirmation!
    end
  end
end

app/controllers/formapagamentos_controller.rb
class FormapagamentosController < ApplicationController
  before_action :set_formapagamento, only: %i[ show edit update destroy ]

  # GET /formapagamentos or /formapagamentos.json
  def index
    @formapagamentos = Formapagamento.where(user_id: current_user.id)
  end

  # GET /formapagamentos/1 or /formapagamentos/1.json
  def show
  end

  # GET /formapagamentos/new
  def new
    @formapagamento = Formapagamento.new
  end

  # GET /formapagamentos/1/edit
  def edit
  end

  # POST /formapagamentos or /formapagamentos.json
  def create
    @formapagamento = Formapagamento.new(formapagamento_params)
    @formapagamento.user_id = current_user.id

    respond_to do |format|
      if @formapagamento.save
        format.html { redirect_to formapagamento_url(@formapagamento), notice: "Formapagamento was successfully created." }
        format.json { render :show, status: :created, location: @formapagamento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @formapagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formapagamentos/1 or /formapagamentos/1.json
  def update
    respond_to do |format|
      if @formapagamento.update(formapagamento_params)
        format.html { redirect_to formapagamento_url(@formapagamento), notice: "Formapagamento was successfully updated." }
        format.json { render :show, status: :ok, location: @formapagamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @formapagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formapagamentos/1 or /formapagamentos/1.json
  def destroy
    @formapagamento.destroy

    respond_to do |format|
      format.html { redirect_to formapagamentos_url, notice: "Formapagamento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formapagamento
      @formapagamento = Formapagamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def formapagamento_params
      params.require(:formapagamento).permit(:forma_pagamento, :numero_cartao, :validade_cartao, :codseguranca, :nomeimpresso)
    end
end

app/helpers/carrinho_helper.rb
module CarrinhoHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/formapagamentos_helper.rb
module FormapagamentosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pedido_helper.rb
module PedidoHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/relatorios_helper.rb
module RelatoriosHelper
end

app/views/formapagamentos/_form.html.erb
<%= simple_form_for(@formapagamento) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :forma_pagamento %>
    <%= f.input :numero_cartao %>
    <%= f.input :validade_cartao %>
    <%= f.input :codseguranca %>
    <%= f.input :nomeimpresso %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/formapagamentos/_formapagamento.html.erb
<div id="<%= dom_id formapagamento %>">
  <p>
    <strong>Forma pagamento:</strong>
    <%= formapagamento.forma_pagamento %>
  </p>

  <p>
    <strong>Numero do Cartão:</strong>
    <%= formapagamento.numero_cartao %>
  </p>

  <p>
    <strong>Validade do Cartão:</strong>
    <%= formapagamento.validade_cartao %>
  </p>

  <p>
    <strong>Código de Segurança:</strong>
    <%= formapagamento.codseguranca %>
  </p>

  <p>
    <strong>Nome impresso no cartão:</strong>
    <%= formapagamento.nomeimpresso %>
  </p>

</div>

app/views/formapagamentos/edit.html.erb
<h1>Editing formapagamento</h1>

<%= render "form", formapagamento: @formapagamento %>

<br>

<div>
  <%= link_to "Mostrar essa forma de pagamento", @formapagamento %> |
  <%= link_to "Voltar para forma de pagamento", formapagamentos_path %>
</div>

app/views/formapagamentos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Formas de pagamento</h1>

<div id="formapagamentos">
  <% @formapagamentos.each do |formapagamento| %>
    <%= render formapagamento %>
    <p>
      <%= link_to "Mostrar essa forma de pagamento", formapagamento %>
    </p>
  <% end %>
</div>

<%= link_to "Nova forma de pagamento", new_formapagamento_path %>

app/views/formapagamentos/new.html.erb
<h1>Nova Forma de Pagamento</h1>

<%= render "form", formapagamento: @formapagamento %>

<br>

<div>
  <%= link_to "Voltar para formas de pagamento", formapagamentos_path %>
</div>

app/views/formapagamentos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @formapagamento %>

<div>
  <%= link_to "Editar essa formas de pagamento", edit_formapagamento_path(@formapagamento) %> |
  <%= link_to "Voltar para formas de pagamento", formapagamentos_path %>

  <%= button_to "Remover essa forma de pagamento", @formapagamento, method: :delete %>
</div>